### ISSUE TITLE
Some issue in http request configuration

### ISSUE THREAD

**Issue by Harsheasy** [typebot-io/typebot-js#2]
### I want to pass UTC today's date and time but in your custom body, it gives an error message. without passing UTC today's date and time I can not get a token of my API

![2021-10-29_10-17-56](https://user-images.githubusercontent.com/77724114/139377428-c4c65505-6ea9-4977-aa4f-64b5948907fd.png)
### I check with the postman application and it is working on that so maybe I am facing a problem from your side

**Comment by Harsheasy** [comment]
curl --location --request POST 'https://webhook.site/45d9d9b9-19a5-48d8-9a84-e71ea79965de' \
--header 'Content-Type: application/json' \
--data-raw '{"createdate":"2021-10-29T04:47:00+00:00"}' 
Try this code on postman then you will receive data like
{
  "createdate": "2021-10-29T04:47:00+00:00"
}
![a11](https://user-images.githubusercontent.com/77724114/139520043-cd51d6b5-5c65-4c7a-9a71-f447c65b1e65.png)


### **BUT** if I try on your typebot then I receive data like which is displayed on the screenshot
![a12](https://user-images.githubusercontent.com/77724114/139520025-988af9d8-0471-4cf5-bd94-386f60f25d5d.png)

### Why your output having slash (\) , because of this I can not connect to my api

**Comment by baptisteArno** [comment]
Hey man, thank you for reporting this. I've just pushed a fix. Let me know if it works 👍

**Comment by Harsheasy** [comment]
Hello, @baptisteArno thanks for solving that issue.
### But I have another problem with the current time and date, I want to pass the current date and time for API so can you help me with that?

**Comment by baptisteArno** [comment]
Unfortunately, you can only pass a variable from the typebot or a static value.

I would suggest you create a cloud function (or a server) that will make this http request with the current date and you'll just have to call this cloud function from Typebot.
